version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  py1:
    lang: python3-http-debian
    handler: ./py1
    image: lyuze/py1:latest
    environment:
      nats_url: nats://nats.openfaas:4222

  # py2:
  #   lang: python3-http-debian
  #   handler: ./py2
  #   image: lyuze/py2:latest

